### ISSUE TITLE
Týmová stránka

### ISSUE THREAD

**Issue by Zoidy23** [Rosta89/letka#13]
Dodělat týmovou stránku:

1. Dodělat role k hráčům, pokud má nějaký číslo, tak zobrazit něco atd..
2. Přidat k hráčům editaci, pokud na to uživatel má právo (admin nebo vlastník týmu asi). Zneaktivnění, zvolení kapitána atd.
3. Přidat logo, zobrazit nějaké defaultní logo, když to žádné nenajde
4. Zobrazit ligy, kterých se tým účastní.
5. Cokoliv dalšího. :)

**Comment by Rosta89** [comment]
Merge pull request https://github.com/Rosta89/letka/pull/21 from Rosta89/Rosta89/issue13
edit hráče ještě není hotov, není hráčová stránka
