### ISSUE TITLE
Administrace ballchasingu

### ISSUE THREAD

**Issue by Zoidy23** [Rosta89/letka#17]
Domyslet, jak by měl obecně fungovat ballchasingu, jestli když někdo nahraje BC replay, tak jestli se to má nějak přejmenovat. Když pak někdo nahraje jen link na svůj replay na BC, tak jestli se to má tahat z něj nebo vytvořit nebo ho reuploadnout. Chtělo by to u toho uploadu pak pohlídat i případ, kdy je zpracování ve frontě. Bylo by dobrý i přidávat automaticky grupy na ballchasingu pro série/ligy.

**Comment by Rosta89** [comment]
Určitě bych ho reuploadnul, pro jistotu, kdyby to on smazal, i když bychom jsme už měli data u nás uložené, tak pro jistotu, jak pohlídat zpracování ve frontě nevím, to už je spíš potom na adminovi(udělat třeba v administraci oznamovnu, kde ti příjde, že když ti od BC příjde jiný status než 204, ten je tuším OK, tak se pošle chybová hláška do oznamovny.

**Comment by Rosta89** [comment]
jinak když příjde 204 od BC, tak nechat ten header na zpracování.
