### ISSUE TITLE
Dodělat stránku match_ballchase

### ISSUE THREAD

**Issue by Zoidy23** [Rosta89/letka#32]
Teď funguje dobře, pokud ten replay je uložený správně a hraje se 3v3, chce to ošetřit případy, kdy např. na jedné straně jsou uložení 4 hráči, je to 2v2 turnaj, je tam hráč z jiného týmu a obecně ten kód udělat nějak přehlednější. Možná by šlo udělat třídu, díky které by se to nějak líp zpracovávalo.
Nebylo by špatný přidat i databázový transakce, kdyby tam byl nějakej problém, tak ať to jde revertovat.

**Comment by Rosta89** [comment]
tak databázový transakce by to chtělo na všech stránkách(hlavně třeba při zakládání ligy).
